-- AlterTable
ALTER TABLE `Article` ADD COLUMN `bury_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `comment_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `digg_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `like_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `read_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `repin_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `share_count` INTEGER NOT NULL DEFAULT 0;
